import path from "node:path";
import { mkdir, writeFile, chmod } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { scaffoldFiles, getHookTemplates, getCiTemplate } from "../scaffold/templates.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// cli.js (собранный) или cli.ts (исходник) лежит на уровень выше commands/
const kitRoot = path.resolve(__dirname, "..");
const kitCliJs = path.join(kitRoot, "cli.js");   // dist/cli.js после build
const kitCliTs = path.join(kitRoot, "cli.ts");   // src/cli.ts при запуске через tsx

export async function initMemory(options: { root?: string; force?: boolean; dryRun?: boolean; installHooks?: boolean; installCi?: boolean } = {}) {
  const root = path.resolve(options.root ?? process.cwd());
  const written: string[] = [];
  const skipped: string[] = [];

  for (const file of scaffoldFiles) {
    const target = path.join(root, file.path);
    if (existsSync(target) && !options.force) {
      skipped.push(file.path);
      continue;
    }
    if (!options.dryRun) {
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, file.content, "utf8");
    }
    written.push(file.path);
  }

  // Install git hooks
  if (options.installHooks) {
    const gitDir = path.join(root, ".git");
    if (!existsSync(gitDir)) {
      console.warn("⚠️  No .git directory found. Skipping hooks installation.");
    } else {
      const hookTemplates = getHookTemplates();
      for (const hook of hookTemplates) {
        const target = path.join(root, hook.path);
        if (!options.dryRun) {
          await mkdir(path.dirname(target), { recursive: true });
          await writeFile(target, hook.content, "utf8");
          await chmod(target, 0o755);
        }
        written.push(hook.path);
      }
    }
  }

  // Install CI
  if (options.installCi) {
    const ciTemplate = getCiTemplate();
    const target = path.join(root, ciTemplate.path);
    if (!options.dryRun) {
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, ciTemplate.content, "utf8");
    }
    written.push(ciTemplate.path);
  }

  // Create memory-contract.json
  const memoryRoot = path.join(root, ".ai", "memory");
  const contractPath = path.join(memoryRoot, "memory-contract.json");
  const contract = {
    version: 2,
    language: "ru",
    requiredTopLevel: [
      "MEMORY.md", "PROJECT.md", "MODULES.md", "ARCHITECTURE.md",
      "TASK_ROUTING.md", "FLOWS.md", "TESTING.md", "OPS.md",
      "GOTCHAS.md", "DECISIONS.md",
    ],
    requiredSubdirs: ["modules", "flows", "decisions", "architecture"],
    dispositions: ["extracted", "rationale-only", "superseded", "historical-only", "rejected", "deferred", "unknown"],
    specialistPhases: ["discovery-semantic", "code-evidence", "rationale-extraction", "quality-review"],
  };
  if (!options.dryRun && (!existsSync(contractPath) || options.force)) {
    await mkdir(memoryRoot, { recursive: true });
    await writeFile(contractPath, JSON.stringify(contract, null, 2), "utf8");
  }

  // Generate wrapper script .ai/atlas/bin/atlas
  // Работает в любом проекте (не требует package.json).
  // Предпочитает dist/cli.js (node), fallback на src/cli.ts через npx tsx.
  const wrapperDir = path.join(root, ".ai", "atlas", "bin");
  const wrapperPath = path.join(wrapperDir, "atlas");
  const hasDist = existsSync(kitCliJs);
  const wrapperExec = hasDist
    ? `exec node "${kitCliJs}" "$@"`
    : `exec npx --yes tsx "${kitCliTs}" "$@"`;
  const wrapperContent = [
    "#!/usr/bin/env bash",
    "# Auto-generated by atlas init. Wrapper for atlas CLI.",
    "# Works without package.json.",
    hasDist
      ? "# Uses compiled dist/cli.js — only requires node in PATH."
      : "# Uses src/cli.ts via tsx — requires npx (npm) in PATH.",
    wrapperExec,
    "",
  ].join("\n");
  if (!options.dryRun && (!existsSync(wrapperPath) || options.force)) {
    await mkdir(wrapperDir, { recursive: true });
    await writeFile(wrapperPath, wrapperContent, "utf8");
    await chmod(wrapperPath, 0o755);
    written.push(".ai/atlas/bin/atlas");
  }

  const packageJsonPath = path.join(root, "package.json");
  const packageHint = existsSync(packageJsonPath)
    ? "Optional: add script \"atlas\": \".ai/atlas/bin/atlas\" to package.json for convenience."
    : "No package.json needed. Use .ai/atlas/bin/atlas directly.";

  console.log(`# Memory scaffold ${options.dryRun ? "plan" : "created"}`);
  console.log(`\nRoot: ${root}`);
  if (written.length) {
    console.log("\n## Written");
    for (const item of written) console.log(`- ${item}`);
  }
  if (skipped.length) {
    console.log("\n## Skipped existing files");
    for (const item of skipped) console.log(`- ${item}`);
  }
  console.log(`\n## Next steps`);
  console.log(`- ${packageHint}`);
  console.log(`- Run: .ai/atlas/bin/atlas validate`);
  console.log(`- Run: .ai/atlas/bin/atlas recall "изменить Agent & Tool Registry"`);
}
